### ISSUE TITLE
Are there other jetImage_7_150p_*.h5 in data

### ISSUE THREAD

**Issue by mk123qwe** [jmduarte/JEDInet-code#2]
Thank you for your great work.
Are there other jetImage_7_150p_*.h5 in data?

**Comment by jmduarte** [comment]
Yes, the full dataset is available here:

up to 150 particles:
https://zenodo.org/record/3602260#.XzjKzxNKjPg

up to 100 particles:
https://zenodo.org/record/3602254#.XzjKxhNKjPh

up to 30 particles:
https://zenodo.org/record/3601436#.XzjLAxNKjPg


Actually some of these datasets are now available in openml datasets, which you can see how to access here: https://github.com/jmduarte/hls4ml-tutorial/blob/master/part1_getting_started.ipynb
